image: trion/ng-cli-karma

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
  - npm install
  - ng build --prod --base-href https://agabor.gitlab.io/NumberLab/
  artifacts:
    paths:
    - dist/

test:
  stage: test
  script:
  - ng test --single-run

pages:
  stage: deploy
  script:
  - mkdir public
  - mv dist/* public
  artifacts:
    paths:
    - public
  dependencies:
  - build
  only:
  - master
