image: trion/ng-cli-karma

pages:
  stage: deploy
  script:
  - npm install
  - ng build --prod
  - mkdir public_html
  - mv dist/* public_html
  artifacts:
    paths:
    - public_html
  only:
  - master
