image: trion/ng-cli-karma

build:
  stage: build
  script:
  - npm install
  - ng build --prod

test:
  stage: test
  script:
  - ng test

pages:
  stage: deploy
  script:
  - mkdir public
  - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
