image: trion/ng-cli-karma

test:
  stage: test
  script:
  - npm install
  - ng test --single-run
  except:
  - master

pages:
  stage: deploy
  script:
  - npm install
  - ng build --prod --base-href https://agabor.gitlab.io/NumberLab/
  - ng test --single-run
  - mkdir public
  - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
