image: trion/ng-cli-karma


job:
  stage: deploy
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - ng build --prod --base-href https://agabor.gitlab.io/NumberLab/
  - ng test --single-run
  - mkdir public
  - mv dist/* public
  artifacts:
    paths:
    - public
  dependencies:
  - build
  only:
  - master
