image: trion/ng-cli-karma

pages:
  stage: deploy
  script:
  - npm install
  - ng build --prod --base-href https://agabor.gitlab.io/NumberLab/
  - mkdir public
  - mv dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
